export default function SurveysPage() {
      return (
          <main className="min-h-screen bg-gray-50">
                <header className="border-b bg-white">
                        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5">
                                  <a href="/dashboard" className="text-2xl font-bold text-gray-900">
                                              Rivo Surveys
                                                        </a>

                                                                  <a
                                                                              href="/wallet"
                                                                                          className="text-sm font-medium text-gray-600 hover:text-black"
                                                                                                    >
                                                                                                                Wallet
                                                                                                                          </a>
                                                                                                                                  </div>
                                                                                                                                        </header>

                                                                                                                                              <section className="mx-auto max-w-7xl px-6 py-10">
                                                                                                                                                      <h1 className="text-3xl font-bold text-gray-900">
                                                                                                                                                                Available Surveys
                                                                                                                                                                        </h1>

                                                                                                                                                                                <p className="mt-2 text-gray-600">
                                                                                                                                                                                          Complete surveys and earn rewards.
                                                                                                                                                                                                  </p>

                                                                                                                                                                                                          <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
                                                                                                                                                                                                                    <div className="rounded-2xl bg-white p-6 shadow-sm">
                                                                                                                                                                                                                                <h2 className="text-xl font-semibold text-gray-900">
                                                                                                                                                                                                                                              Survey Example
                                                                                                                                                                                                                                                          </h2>

                                                                                                                                                                                                                                                                      <p className="mt-2 text-sm text-gray-500">
                                                                                                                                                                                                                                                                                    Estimated time: 5 minutes
                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                            <div className="mt-5 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                          <span className="text-lg font-bold text-gray-900">
                                                                                                                                                                                                                                                                                                                                          $0.50
                                                                                                                                                                                                                                                                                                                                                        </span>

                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                      type="button"
                                                                                                                                                                                                                                                                                                                                                                                                      className="rounded-lg bg-black px-5 py-2.5 text-sm font-medium text-white hover:bg-gray-800"
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                    Start survey
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-2xl bg-white p-6 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-semibold text-gray-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Consumer Survey
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="mt-2 text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Estimated time: 10 minutes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-5 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-lg font-bold text-gray-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $1.25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-lg bg-black px-5 py-2.5 text-sm font-medium text-white hover:bg-gray-800"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Start survey
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
